// Main page dictionnary
var mainpage = {
    'さんがレリックを奪われたわ!ギルドリベンジのチャンスよ!' : ' has been attacked ! You can avenge him in the Rating Game!',
    'ギルド掲示板に新しい投稿があります' : 'New guild message !',
    '新着情報はありません' : 'No news',
    '友情ガチャが回せます' : 'Your daily FREE Friend Gacha has arrived !',
    'プレゼントが届いています' : 'There\'s still items in your Gift Box !',
    'ギルドへの勧誘がきています' : 'You have a guild invitation pending !',
    '期間限定イベント開催中!4/18(月)10:59まで' : 'Limited event ! Ends  4/18 (Monday) 10:59 !',
    '割り振りPtがあります' : 'There are Stats points waiting to be allocated !',
    '余っている割り振りPtがあるようね。早速割り振ってデッキを強くするのよ!' : 'You have some Stats points to allocate.',
    '友情Ptがたまってるわね。さっそく引いてごらんなさい！' : 'You\'ve got a lot of Friend points, you should use some of them !',
    '贈り物が届いているわ、プレゼントBOXから受け取るのよ！' : 'There\'s items waiting in your Gift Box !',
    '行動力不足応援要請がきています' : 'A friend is asking for AP gift !',
    '友情Ptがたまってるわね。さっそく引いてごらんなさい！' : 'You\'ve got a lot of Friend points, you should use some of them !',
    'あいさつを返す' : 'Reply',
    'レーティングゲームでレリックをたくさん獲得するわよ！' : 'You can earn relics in the Rating Game !',
    '友達申請がきています' : 'You received a friend request !',
    'さんがギルドに加入したわ!あいさつして交流を深めるのよ!' : ' has joined the guild ! Feel free to get acquainted !',
    'が友達になりました' : ' is now your friend !',
    '行動力：' : 'AP: ',
    '魔力：' : 'MP: ',
    '友情Pt：' : 'Friend PT: ',
    '信頼度がMaxになったカードがあります' : 'A card has reached max reliability !',
    'ピース：' : 'Money: ',
    'カード：' : 'Cards: ',
    'コンプリート報酬が受け取れます' : 'Relic set reward pending !',
    '新しいあいさつがあります' : 'You received a new message !',
    'ギルドボス出現中!' : 'Guild Boss !',
    'レイドボス出現中!' : 'Boss !',
    '逃亡まで' : 'Time left: ',
    'ギルドボス出現中！' : 'A raid battle is available !',
    'レイドボス出現中！' : 'A raid battle is available !',
    // Event 26-04
    '期間限定イベント開催中!4/26(火)10:59まで' : 'Limited event available until 4/26 (Tuesday) 10:59.',

    // Slider
    'イベント限定ガチャにSSRゼノヴィア、アーシア追加!4/26(火)10:59まで' : 'Limited Time SSR cards Asia and Zenovia added to the event ! (End on Tuesday 4/26, 10:59AM)',

    // News (can be deleted after a while)
    '【更新】「温泉旅館で極楽です!」' : '【Update】 Hot bath event', 
    '【開始】「温泉旅館で極楽です!」' : '【Start】 Hot bath event',
    '【終了】「SEXYビスチェで、アフターパーティーです!!」' : '【End】 Sexy bustier event',
    '【更新】「SEXYビスチェで、アフターパーティーです!!」' : '【Update】 Sexy bustier event',
    '【予告】「温泉旅館で極楽です!」' : '【Note】 Hot bath event incoming',

    // News 2 (can be deleted after a while)
    'イベント限定ガチャにSSR[湯けむりⅢ]シュリヤー、小猫追加!' : 'Koneko card added to the event Gacha !',
    '「合成EXP2倍キャンペーン」（4/23まで）' : 'Synthesis Exp x2 until 23/04 ! !',
    'イベント限定ガチャにSSRゼノヴィア、アーシア追加!' : 'Asia and Zenovia cards added to the event Gacha !',
    '「合成EXP2倍キャンペーン」（4/21まで）' : 'Synthesis EXP x2 (until 4/21)',
    'Infinity[自撮りⅡ]リアス登場!「リアス部長の悩殺セルフィーBOXガチャ」' : 'New Gacha: Rias Selfie !',
    'ガチャ告知アニメーション内誤表記のお詫び' : 'Erratum about Zenovia\'s overboost effects',
    'レアメダルの誤配布に関するお詫び' : 'Appology about an error in the event',
    'iOS9、スマートフォンのOSについてのお知らせ' : 'iOS9 and other OS information',
    '運営からのメールが届かない場合の改善方法' : 'If you don\'t receive our emails',
    '不正行為・迷惑行為について' : 'About fraud and nuisances',
    '重要なお知らせ' : 'Important informations',
    'マイページへ' : 'To Main Page',
    'ヘルプ' : 'FAQ',

};

// Statpoints allocation page http://g12014827.sp.pf.mbga.jp/?url=http%3A%2F%2Fmb.hsdd.maql-games.jp%2Fsp%2Fallocate.html
var statpoints = {
    '割り振りPtの割り振りが完了しました' : 'Stats points allocated !',
    '行動力' : 'Maximum AP',
    '攻撃コスト' : 'Attack deck size',
    '防御コスト' : 'Defense deck size',
    'クエスト' : 'Back to quests',
    '30割り振りPt' : '30 points',
    '割り振りPtが足りません。' : 'Max 30 points at a time !',
    'レーティングゲーム' : 'Back to Rating Games',
    'デッキを編集する' : 'Edit your decks',
    '上記内容で割り振る' : 'Allocate as seen above',
    '自動割り振り' : 'Automatic allocation (not recommended)',
    'ステータス' : 'Stats points',
    '割り振りPt' : 'Allocation point',
    '※一度に割り振れるのは' : '※You can only use up to ',
    'までです' : ' at a time',
};

// Guild
var Guild = {
    '掲示板をみる' : 'Back to message board',
    'ギルド掲示板投稿' : 'Post a guild message',
    'ギルド掲示板' : 'Guild message board',
    'ギルドリーダー' : 'Guild leader',
    'ギルドメンバー　' : 'Guild members',
    '貢献度Pt:' : 'Contribution:',
    '自動受入不可' : 'Non-automatic validation',
    '自動受入可' : 'Automatic validation',
    '自動受入' : 'Recruitment',
    '注意事項' : 'Notes',
    'ギルド加入申請を出す' : 'Apply to the guild',
    'ＨＰ20%増加中！' : 'Increase HP by 20% !',
    '防御障壁：' : 'Defense barrier:',
    'ギルドガチャについて' : 'About guild Gacha',
    '◆本名、メールアドレス、電話番号などの個人情報や個人の特定に繋がる情報は入力しないでください' : '◆Do not post personnal informations like Name, Phone, Bank Cards,...',
    '過去の履歴' : 'Previous history',
    '古い順' : 'Sorted by joining date',
    '(次のLvまで' : '(Next level in ',
    '貢献度順 ' : 'Sorted by contribution',
    '累計ギルドPt' : 'Guild points',
    'ギルドレベル' : 'Guild level',
    'ギルドガチャPt' : 'Guild points',
    'ギルドガチャを引く' : 'Draw a guild card',
    'ギルドガチャPt' : 'Guild gacha points',
    'メンバー行動履歴' : 'Members action history',
    '[自動処理]' : '[Automatic]',
    'さんがギルドに加入しました。' : ' has joined the guild !',
    'さんをギルドから除名しました。' : ' has been excluded.',
    'さんがギルドを脱退しました。' : ' has left the guild.',
    '行動履歴は14日間表示されます' : 'Action history covers last 14 days.',
    'ギルドトップ' : 'Guild page',
    'ギルド紹介文' : 'Guild information',
    'ギルドメンバー一覧' : 'Guild members list',
    'ギルドメニュー' : 'Guild menu',
    'ギルドメンバーを誘う' : 'Send guild invitations',
    '勧誘中のユーザーを確認する' : 'View pending guild applications',
    'ギルドから脱退する' : 'Leave the guild',
    'ギルドとは' : 'Guild FAQ',
    '投稿する' : 'Send',
    '過去の投稿' : 'Older posts',
    '出現カードリスト・出現確率' : 'Check guild gacha lineup',
    'ギルド情報' : 'Guild informations',
    '所属ギルド名:' : 'Guild name: ',
    'ギルドメンバー数:' : 'Guild members: ',

};

// Guild invit received
var Guildinvit = {
    'ギルド勧誘一覧へ' : 'Back to guild solicitations',
    'ギルド勧誘一覧' : 'Guild invitation list',
    'ギルドレベル：' : 'Guild lv:',
    'ギルドリーダー：' : 'Guild leader:',
    '承認する' : 'Approve',
    '拒否する' : 'Deny',
    '勧誘を拒否しました。' : 'You declined the invitation.',
    'ギルド勧誘拒否完了' : 'Guild solicitation declined !',

};

// Friendlist
var friendlist = {
    'Lv昇順で並べ替え' : 'Sort by lvl (ascending order)',
    'Lv降順で並べ替え' : 'Sort by lvl (descending order)',
    '最終ログイン早い順で並べ替え' : 'Sort by last connection (newest to oldest)',
    '最終ログイン遅い順で並べ替え' : 'Sort by last connection (oldest to newest)',
    '無所属' : 'Without guild',
    '友達とは' : 'Friends FAQ',
    '友達リストから外す' : 'Remove friend',
    '最終ログイン' : 'Last time online',
    '友達を増やして、ゲームをもっと楽しみましょう。' : 'Here\'s your friendlist !',
    '友達が多いほど最大コストも多くなるわ。' : 'You and your friends will be able to help each other defeating boss and raid boss.',
    '登録できる友達数はレベルの上昇によって増えていくのよ。' : 'Each friend you have give you 3 Allocation points. The size of your friendlist increase as you gain levels.',
    '友達登録数 ' : 'Friendlist size',
    'あいさつ履歴' : 'Message history',
    '友情Ptとは' : 'Friend points FAQ',
    '申請を取り消す' : 'Cancel the invitation',
    '友達リストへ' : 'Back to friend list',
    '承認する' : 'Confirm',
    '断る' : 'Deny',
    '友達申請承認' : 'Friend request approval',
    '友達申請の承認が完了しました。' : 'You now have one more friend !',
    'クエスト' : 'Quests',

    '友情Pt' : ' Friend points',
    '友達リスト' : 'Friend list',
    '所属' : '',
    '友達へのお誘いを取り下げました。' : 'Friend request cancelled.',
    'お誘い取り下げ完了' : 'Cancelling friend request',
    'あいさつ' : 'Send a message',
    '友達を探す' : 'Search friends',
    '友情Ptとは' : 'Friend points FAQ',
    '友達から外す' : 'Removing a friend',
    'さんを友達から外しますがよろしいですか？' : ' will be removed from your friends. Are you sure you want to do that ?',
    'お誘いの取り下げ' : 'Cancelling friend invitation',
    'さんへの友達へのお誘いを取り下げます。' : ' won\'t be able to accept your request anymore.',
    '取り下げる' : 'Confirm',
    '友達申請の承認完了' : 'One more friend !',
    'さんからの友達申請を承認しますがよろしいですか？' : ' will be added to your friends. Are you sure you want to accept this invitation ?',
    'よろしいですか？' : 'Are you sure you want to cancel your invitation ?',
    '登録済' : 'Friends',
    '申請中' : 'Pending',
    '承認待ちのユーザはいません' : 'There is no friend application waiting for your approval.',
    '承認待' : 'Waiting your approval',  
    'ギルド勧誘' : 'Guild inv.',
    'ギルド' : 'Guild',
};

// Quest progression
var quest = {
    '友達申請' : 'Friend request',
    'ギルド勧誘' : 'Guild request',
    'と出会った！' : 'has been encountered !',
    'レアリティ：' : 'Rarity: ',
    '獲得ピース' : 'Money per action',
    'を手にいれた！' : 'was just found !',
    'カード枚数：' : 'Cards owned:',
    '戻る' : 'Back',
    '残り' : 'Time left ',
    'レベルアップ' : 'Level Up !',
    '今だけ獲得EXP2倍！' : 'Limited time EXP x2 !',
    '・割り振りPt' : '・Allocations points ',
    '行動力 、魔力が全回復した！' : 'Your AP bar is filled up.',
    '行動力' : 'AP ',
    'もうすぐカード所持数が上限に達します。' : 'Your card reserve is nearly full !',
    'カード所持数が上限を超えたため売却しました。' : 'That card has been sold because your card reserve was full !',
    'ピース' : 'Money:',
};

// Quest page dictionnary http://g12014827.sp.pf.mbga.jp/?url=http%3A%2F%2Fmb.hsdd.maql-games.jp%2Fsp%2Fquest_select.html
var questselect = {
    '今しか遊べない限定イベント!' : 'Play the limited time event !',
    '限定スペシャルカードや豪華アイテムをGETしよう!' : 'Try to get special cards and amazing rewards !',
    'メインシナリオを進めよう!!' : 'Play through the scenario and make Ddraig proud of you !',
    'ノーマルクエスト' : 'Quest',
    'イベント開催中' : 'Event available',

};

// Raid
var raid = {
    '逃亡までの残り時間' : 'Sort by time remaining',
    'レイドボスのLv' : 'Sort by boss LVL',
    '残りHPが高い順' : 'Sort by HP left (Descending)',
    '残りHPが低い順' : 'Sort by HP left (Ascending)',
    '発見者:' : 'Found by ',
    '撃破者:' : 'Defeated by ',
    '残り時間:' : 'Time left:',
    '出現レイドボス一覧' : 'Raid boss',
    '自分が遭遇' : 'Your Boss',
    'ギルドレイド' : 'Guild boss',
    '救援に向かう' : 'Fight',
    '現在レイドボスは' : 'No boss at the moment.',
    '出現していません。' : 'They\'re probably afraid of the Red dragon emperor !',
    '救援要請' : 'Friend\'s boss',
    'イベントトップ' : 'Back to events',
    '更新する' : 'Refresh',
    '撃破成功' : 'Defeated on',
    '逃亡しました' : 'Fled',
    'ボスと戦う' : 'Attack !',

};

// Quest out of AP http://g12014827.sp.pf.mbga.jp/?url=http%3A%2F%2Fmb.hsdd.maql-games.jp%2Fsp%2Fevent150_quest_shortage_active.html
var Outofap = {
    '行動力不足' : 'Lack of action points',

    '友達に応援要請を送りました。' : 'You asked your friends to send you AP.',
    '次回の応援要請は' : 'Your next available request will be on',
    'に使用できます。' : '',
    '友達に応援を要請する' : 'Ask your friends for AP Gift',
    '行動力が尽きてしまったみたいね。' : 'You\'re out of Action points.',
    '行動力は時間がたてば徐々に回復していくわ。' : 'You\'ll recover your Action points over time.',
    '全回復まであと ' : 'Your AP will be full in ',
    '分' : ' minutes.',
    'フェニックスの涙を' : 'Use ',
    '個使う' : " Phenix tears",
    '行動力100%回復' : 'Regain 100% of your AP',
    '所持数：' : 'You have: ',
    '使う' : 'Use',
    'キャンセル' : 'Cancel',
    'フェニックスの涙を1個使用しますか？' : 'Are you sure you want to use 1 Phenix tears ?',
    'フェニックスの涙(小)を1個使用しますか？' : 'Are you sure you want to use 1 small Phenix tears ?',
    'フェニックスの涙(小)を2個使用しますか？' : 'Are you sure you want to use 2 small Phenix tears ?',
    'フェニックスの涙(小)を3個使用しますか？' : 'Are you sure you want to use 3 small Phenix tears ?',
    'フェニックスの涙(小)を4個使用しますか？' : 'Are you sure you want to use 4 small Phenix tears ?',
    'フェニックスの涙(小)を5個使用しますか？' : 'Are you sure you want to use 5 small Phenix tears ?',
    'よ。' : '',
    'フェニックスの涙(小)：残り' : 'Small Phenix tears: ',
    '個' : ' units',
    'フェニックスの涙：残り' : 'Phenix tears: ',
    '合成' : 'Synthesis',
    '進化' : 'Evolution',
    'クエストTOP' : 'Back to quests',
    'イベントTOPへ' : 'Back to event',
    'レーティングゲーム' : 'To the Rating Games',

};

// AP Request http://g12014827.sp.pf.mbga.jp/?url=http%3A%2F%2Fmb.hsdd.maql-games.jp%2Fsp%2Fquest_request_rescue_list.html

var apRequest = {
    'するのよ!' : ' It only takes few seconds !',
    '応援した分、' : '',
    '応援依頼はありません。' : 'There\'s no AP gift request pending',
    '全員を応援して行動力回復' : 'Giving AP to everyone !',
    '友達を応援すると応援した友達の行動力が' : 'Give AP to your friends !',
    '5回復' : ' 5 AP are given to each friend in the list !',
    'あなたの行動力も回復' : 'You also receive the same amount of AP you gifted !',
    'するわ!' : '',
    '応援要請が届きました' : 'Asked for AP !',
    '応援成功回数：' : 'Received:',
    '応援成功率：' : 'Rate:',
    '応援依頼' : 'Friends AP requests',
    '応援要請' : 'Your AP request',
    '応援リスト' : 'AP Gift page',

};


// Rating game http://g12014827.sp.pf.mbga.jp/?url=http%3A%2F%2Fmb.hsdd.maql-games.jp%2Fsp%2Ftreasure_battle.html%3FchkLogin%3Dtrue
var ratingGame = {
    'ギルド貢献度Pt' : 'Guild contribution point',
    ' レーティングゲームトップ ' : 'Go to the rating games',
    '☆今だけ獲得ギルドガチャPt2倍☆' : '☆ Guild Gacha X2 Limited Time !☆',
    'コンプリート特典を受け取る' : 'Receive relic\'s set reward',
    ' 続けてリベンジする' : 'Back to revenge',
    '期間限定!獲得ギルドガチャPt2倍!!' : 'Limited time ! Get Guild Gacha Points x2 !!',
    '同じ相手には1日3回までしか攻撃できません。(リベンジは含みません)' : 'You can only attack someone 3 times per day. (This doesn\'t include revenges)',
    '対戦相手を更新' : 'Refresh opponents list',
    '秘密の招待状 コンプリート報酬' : 'Secret Invitation set Rewards',
    'レーティングゲームとは' : 'Rating game FAQ',
    'レリックを変更する' : 'Choose another relic set',
    '所持数' : 'Progress:',
    'コンプ回数' : '| # of completion: ',
    '魔力全回復まであと' : 'Your MP will be full in ',
    'ランキング' : 'Ranking',
    '戦闘履歴' : 'Fight History',
    'レーティングゲーム' : 'Rating Games',
    'おすすめのシリーズ' : 'Selected relic set',
    'シリーズ' : ' Series',
    '聖水' : 'Holy Water',
    '秘密の招待状' : 'Secret invitation',
    '目覚まし時計' : 'Issei\'s alarm clock',
    'オカ研ハチマキ' : 'ORC Headband',
    'ラッチュー君' : 'Mr. Rachu',
    '聖書' : 'Holy Bible',
    '十字架' : 'Holy Cross',
    '別の対戦相手を探す' : 'Fight another opponent',
    'を獲得しました。' : ' earned.',
    'ピース' : ' Money',
    'ギルドPt' : 'Guild points',
    'あと1つでコンプリート' : 'Only one more to complete !',
    'あと2つでコンプリート' : 'Two more to complete !',
    'あと3つでコンプリート' : 'Three more to complete !',
    'あと4つでコンプリート' : 'Four more to complete !',
    'あと5つでコンプリート' : 'Five more to complete !',
    '結界魔法陣を購入する' : 'Buy def. scroll',
    '対戦相手を探す' : 'Fight an opponent',
    'リベンジ' : 'Revenge ',
    '対戦' : 'Fight',
    '友達数：' : 'Friends: ',
    '(赤)' : '(Red)',
    '(紫)' : '(Purple)',
    '(青)' : '(Blue)',
    '(水)' : '(Turquoise)',
    '(緑)' : '(Green)',
    '(黄)' : '(Yellow)',
    '分' : ' minutes',
    '戦闘力:' : 'Total ATK: ',
    '(防御障壁効果' : '(Guild boost ',
    'ドラゴンの血(小)を使う' : 'Use a small Dragon blood',
    '（残り' : '(You have ',
    '個）' : ' units)',
    'ドラゴンの血を使う' : 'Use a Dragon blood',
    '戦闘力：' : 'ATK: ',
    '友達の力を借りて攻撃' : 'Use your sacred gear',
    '通常攻撃' : 'Attack',
    '魔力20' : '- 20 MP',
    '魔力40' : '- 40 MP',
    'バトルアニメーションをスキップ' : 'Skip fight animations',
    '別のレリックを狙う ' : 'Choose another relic set',
    '魔力' : 'Mp',
    '個' : ' unit(s)',
    '詳細結果' : 'Result details',
    '【発動スキル】' : '【Skills trigered:】',

};

// Rating games ranking http://g12014827.sp.pf.mbga.jp/?url=http%3A%2F%2Fmb.hsdd.maql-games.jp%2Fsp%2Ftreasure_battle.html%3Faction%3Dranking
var ratinggameRanking = {
    ' レーティングゲームトップ ' : 'Go to the rating games',
    '周辺を見る' : 'view your rank',
    '勝利数：' : 'Wins:',
    '-攻撃：' : '- as attacker: ',
    '-防衛：' : '- as defenser: ',
    'レーティングゲームランキング】' : 'Rating games ranking】',
    'ランキングは月内に1度以上戦わないと表示されません' : 'To be ranked, you need to fight at least one time.',
    'ランキングは表示月内に1度以上戦わないと表示されません' : 'Stats are only available for months were you fight at least 1 time.',
    '更新(1日毎に更新)' : ' (Updated every day)',
    '勝' : ' Wins ',
    '攻撃:' : 'As attacker: ',
    '防衛:' : 'As defenser: ',
    '敗' : ' Defeats ',
    '戦' : ' Fight ',
    'レーティングゲーム' : 'Rating Games',
    '位' : '#',



};

// Paid GACHA http://g12014827.sp.pf.mbga.jp/?url=http%3A%2F%2Fmb.hsdd.maql-games.jp%2Fsp%2Fgacha.html%3FchkLogin%3Dtrue
var paidGacha = {
};


// Sitri GACHA http://g12014827.sp.pf.mbga.jp/?url=http%3A%2F%2Fmb.hsdd.maql-games.jp%2Fsp%2Fgacha.html%3Fgacha_mode%3Dticket
var sitriGacha = {

};

// Cards
var cards = {
    'バランス・ブレイクを続ける' : 'Balance break again',
    '24時間限定! 合成の獲得EXP2倍!' : 'Get EXP x2 for 24H only !',
    'バランス・ブレイク' : 'Proceed the Balance break !',
    'さらに進化させる' : 'To further evolve !',
    'このカードを強化する' : 'Upgrade this card (sockets)',
    'を受け継いだ' : ' gained !',
    '※進化するとLvとスキルLvが1になります' : '※Note that upon evolution, Card LV and Skill LV will be set to 1 !', 
    'ソケットにブーストアイテムをセットしよう。すでにセットしている場合は、ブーストアイテムを上書きします。' : 'You can apply boost to sockets. If a socket is already used, the boost will override existing one.',
    '禁手 バランス・ブレイカーBorN' : 'Balance Breaker (BorN)',
    'MAXレベルまで強化合成しているBorNカードに使用することで、レベル上限を1アップすることができます' : 'Using this item on a BorN card will increase his max level by 1. Note that there\'s a limit on how many levels you can add this way.',
    '禁手 バランス・ブレイカー∞' : 'Balance Breaker (∞)',
    'MAXレベルまで強化合成している∞カードに使用することで、レベル上限を1アップすることができます' : 'Using this item on a ∞ card will increase his max level by 1. Note that there\'s a limit on how many levels you can add this way.',
    '禁手 バランス・ブレイカーW' : 'Balance Breaker (W)',
    'MAXレベルまで強化合成しているWカードに使用することで、レベル上限を1アップすることができます' : 'Using this item on a W card will increase his max level by 1. Note that there\'s a limit on how many levels you can add this way.',
    '禁手 バランス・ブレイカーUR' : 'Balance Breaker (UR)',
    'MAXレベルまで強化合成しているURカードに使用することで、レベル上限を1アップすることができます' : 'Using this item on a UR card will increase his max level by 1. Note that there\'s a limit on how many levels you can add this way.',
    '禁手 バランス・ブレイカーSSR' : 'Balance Breaker (SSR)',
    'MAXレベルまで強化合成しているSSRカードに使用することで、レベル上限を1アップすることができます' : 'Using this item on a SSR card will increase his max level by 1. Note that there\'s a limit on how many levels you can add this way.',
    '禁手 バランス・ブレイカーSR' : 'Balance Breaker (SR)',
    'MAXレベルまで強化合成しているSRカードに使用することで、レベル上限を1アップすることができます' : 'Using this item on a SR card will increase his max level by 1. Note that there\'s a limit on how many levels you can add this way.',
    'カード詳細' : 'Card details',
    'カードリスト' : 'Card list',
    'カードの並び替え' : 'Card ordering',
    'カードID順' : 'Sort by Card #',
    '入手が新しい順' : 'Newest first',
    '入手が古い順' : 'Oldest first',
    'レアリティが高い順' : 'Rarity (Born to Common)',
    'レアリティが低い順' : 'Rarity (Common to Born)',
    '戦闘力が高い順' : 'Attack value (descending order)',
    '戦闘力が低い順' : 'Attack value (ascending order)',
    'HPが高い順' : 'Health points (descending order)',
    'HPが低い順' : 'Health points (ascending order)',
    'Lvが高い順' : 'Level (descending)',
    'Lvが低い順' : 'Level (ascending)',
    'デッキコストが高い順' : 'Card cost (descending)',
    'デッキコストが低い順' : 'Card cost (ascending)',
    '悪魔の駒を昇順(Ki→P)' : 'Pieces type (King to Pawn)',
    '悪魔の駒を降順(P→Ki)' : 'Pieces type (Pawn to King)',
    '進化可能なカードのみ' : 'Evolvable card only',
    'オーバーブーストカード以外' : 'Non overbooster cards',
    '進化度:' : 'Stade:',
    '進化しないカードです' : 'Can\'t further evolve !',
    '進化度1のみ' : 'Evolution stade 1 Only',
    'スキルLvUP確率：' : 'Skill LvUp chance: ',
    '進化度' : 'Evolution stade',
    'ベースカードに選択する' : 'Select this card',
    'このカードを売却する' : 'Sell this card',
    'レアリティの高い順で優先的に選出されています' : 'Cards will be used by ascending order.',
    '合成によってベースカードの成長度が100%を越える分の消費カードは除外されています。' : 'Cards will not be used once the selected card reach max level.',
    'アニメーションをスキップ' : 'Skip synthesis animation',
    '同じ悪魔の駒ボーナス!対象カードの合成獲得EXP1.5倍!' : 'EXP x1.5 when the consummed card is the same as the selected.',
    '信頼度' : 'Reliability',
    'タッチしてみる' : 'Touch !',
    '端末をシェイクしてぷるるん!' : 'You can also shake the terminal !',
    '※端末の機種やブラウザによっては揺れない場合があります。' : '※May not work depending on terminal & browser.',
    '成長度' : 'XP bar',
    '戦闘力' : 'Attack',
    '合成素材確認' : 'Synthesis confirmation',
    '以下のカードを素材にします' : 'Cards below will be destroyed during process',
    '全ページのカードを一括合成' : 'Use all sorted cards for synthesis',
    '合成素材選択' : 'Synthesis choice',
    'ｾｲｸﾘｯﾄﾞｷﾞｱで合成' : 'Use sacred gear',
    'カード合成' : 'Use cards',
    'ページ内全選択' : 'Select/Unselect all',
    'ピースが少なくなったらクエストで稼ぐか要らないカードを売却するといいわ。' : 'You can also sell the cards you don\'t need ! ',
    '売却する' : 'Sell',

    '合成用アイテムとは' : 'Synthesis material FAQ',
    '合成とは' : 'Synthesis FAQ',
    'セイクリッドギアとは' : 'Sacred Gear FAQ',
    '詳細を確認' : 'Reincarnation details',
    'セイクリッドギア' : 'Sacred Gear',
    'カードに合成することで、効率良く成長させることができます' : 'Used as synthesis material to give Experience to your evil pieces. Each gives 100 Experience.',
    'チケットでレアカードを手に入れよう!' : '',
    '詳細' : 'Details',
    '強化素材選択' : 'Available upgrades',
    '効果' : 'Effect: ',
    '戦闘力' : 'Attack ',
    '強化する' : ' points',
    '空きスロット' : 'Empty socket',
    'ソケット' : 'Socket',
    '空' : 'Empty',
    'コスト' : 'Cost',
    '効果：' : 'Effect:',
    '※このアイテムではスキルレベルは上昇しませんのでご注意下さい': '※ Note that sacred gear can\'t be used for skill leveling.',
    'アイテムを使用する必要はありません。' : 'Can\'t use that item on this card.',
    '所持数' : 'Owned:',
    'スキルLv：' : 'Skill lv:',
    'スキル：' : 'Skill:',
    'カードコレクションを確認' : 'Check card collection',
    'デッキ編成' : 'Deck Organization',
    'このカードを合成する' : 'Synthesis this card',
    'このカードを強化する' : 'Upgrade this card (sockets)',
    '悪魔の駒を変更' : 'Promotion',
    'このカードを保護する' : 'Enable card protection',
    'このカードを保護しない' : 'Cancel card protection',
    '攻撃デッキに優先配置する' : 'Enable offensive priority',
    '攻撃デッキに優先配置しない' : 'Disable offensive priority',
    '防御デッキに優先配置する' : 'Enable defensive priority',
    'このカードを売却する' : 'Sell this card',
    'このカードをコレクションに収納する' : 'Deposit card in Collection',
    'アルバム' : 'Album',
    'カードコレクション一覧' : 'Card collection list',
    'このカードをリーダーにする' : 'Make this your representant',
    'オーバーブーストカード' : 'Overbooster cards',
    'C以下' : 'C',
    'UC以下' : 'UC and below',
    'R以下' : 'R and below',
    'HR以下' : 'HR and below',
    'SRのみ' : 'SR only',
    'SSRのみ' : 'SSR only',
    'URのみ' : 'UR only',
    'Ｗのみ' : 'Ｗ only',
    '∞のみ' : '∞ only',
    'BorNのみ' : 'BorN only',
    'レベル1のみ' : 'Level 1 Only',
    'ボイス付き' : 'With voice',
    '全て' : 'All',
    '売値' : 'Selling price ',
    'LvMAXで手に入れられるブーストアイテム' : 'Rewards once at max LV.',
    '進化1' : 'Stade 1',
    '進化2' : 'Stade 2',
    '進化3' : 'Stade 3',
    '進化4' : 'Stade 4',
    '合成を続ける' : 'Synthesis again',
    'このカードを進化させる' : 'Evolve this card',
    'このカードをバランス・ブレイクする' : 'Balance break this card',
    '合成完了' : 'Synthesis result',
    'スキル発動率' : 'Skill trigger rate',
    'スキル' : 'Skill',
    '効果' : 'Effect',
    '転生進化カード' : 'Reincarnate cards',
    '転生進化とは' : 'Reborn FAQ',
    '転生進化' : 'Reborn',
    '合成' : 'Synthesis',
    'ジョーカー進化とは' : 'Joker evolution FAQ',
    '進化とは' : 'Evolution FAQ',
    'カード進化' : 'Card evolution',
    'アイテムがありません' : 'No material available.',
    'ジョーカー進化' : 'Joker evolution',
    '強化とは' : 'Upgrade FAQ',
    '強化' : 'Upgrade',
    'バランス・ブレイクとは' : 'Balance Breaker FAQ',
    'バランス・ブレイク素材選択' : 'Balance breaker choice',
    '該当カードなし' : 'No cards meeting the search criterias',
    'バランス' : 'Balance',
    'ブレイク' : 'Breaker',
    '追加が新しい順' : 'Newest reincarnation first',
    '追加が古い順' : 'Old reincarnation first',
    '詳細を確認' : 'See the details',
    '進化素材選択' : 'Evolution choice',
    '進化完了' : 'Evolution result',
    '進化素材確認' : 'Evolution confirmation',
    '引き継ぎます' : ' (expected increase)',
    '進化' : 'Evolution',
    '売却' : 'Card list',
    'アルバム' : 'Album',
    'ベースカードを変更する' : 'Choose another card',
    'ベースカード選択' : 'Base card selection',
    '素材選択へ戻る' : 'Back to selected card',
    'ベースカード' : 'Selected card',
    '戻る' : 'Back to material choice',
    '下記カードは表示されません' : 'Following cards aren\'t displayed: ',
    'リーダーに指定されているカード' : 'Leader card',
    '保護されているカード' : 'Protected cards',
    'デッキに配置しているカード' : 'Cards that are in your decks',
    '枚' : ' more cards',
    '個' : 'Unit(s)',
    'レアリティ' : 'Rarity',
    'を' : '+',
    '他' : '+ ',

};


// GiftBox
var giftBox = {
    'レジェンドチケット' : ' Legendary ticket',
    'ピース' : ' Money',
    'セイクリッドギア' : ' Sacred Gear',
    'ガチャをまわす' : 'Go to gacha',
    '禁手 バランス・ブレイカ' : 'Balance Breaker',

    '■以下のものを受け取りました' : 'You received the following:',
    '◆プレゼントBOX状況': '◆Gift box state',
    '友情P&その他(' : 'Friends points & others : (',
    '友情Pt&その他引き取り履歴' : 'history',
    'アイテム一覧へ' : 'Go to your inventory',
    '受取可能なアイテムが存在しません。' : 'Gift box is empty !',
    '※注意事項' : '※Notes',
    '【重要】プレゼントBOX仕様変更につきまして' : '[IMPORTANT]Gift box changes ; please read !',
    'プレゼントBOXの受取容量はカードのみで1000件、友情Pt&その他で1000件です。' : 'You can have 1000 items for each category maximum.',
    '・ボタンを連打するとエラーになる場合があります。' : 'Errors can occur in some cases.',
    '90日間' : 'Items can stay in the Gift box for 90 days',
    '・プレゼントの受け取りには有効期限があります。' : '・Items in the Giftbox have an expiration date.',
    'を経過するとプレゼントBOXから消滅します｡' : '',
    'プレゼントBOXの容量が1000件を超えた場合' : 'If your box exceeds 1000 items limits,',
    'フェニックスの涙(小)' : 'Small Phenix tears',
    'ドラゴンの血(小)' : 'Small Dragon blood',
    'ドラゴンの血' : 'Dragon Blood',

    '【一時保管所とは】' : '[What\'s the temporary box ?]',
    '・設置期限を過ぎると一時保管所のカード/アイテムは全て削除されます。' : 'Please, note there\'s a time limit to retrieve items from the Temporary box.',
    '・一時保管所にあるアイテム/カードはプレゼントBOXに移動することができます。' : '・Items in the temporary box will move to the Gift box.',
    'プレゼントBOXから受け取ることで使用出来るようになります。' : 'You just have to retrieve items in the Gift box.',
    '・2/29(月)の仕様変更時に消失したアイテム/カードが保管されます。' : '2/29(Monday) - lost items should appear in the Temporary box.',
    '・一時保管庫の使用期限は' : 'Please, note that ',
    '古いものから消滅' : ' oldest items',
    'されます。' : ' will be lost.',
    'プレゼント受取から30日間分の履歴が表示されます。' : 'History only show up to 30 days.',
    'プレゼント受取履歴' : 'Received items history',
    '贈り物が届いているわ。' : 'You have item in your Gift box !',
    '受け取って確認するのよ。' : 'I wonder what they are !',
    ' ページ内全選択' : 'Select all',
    'チェックしたものを受け取る' : 'Retrieve checked items',
    '受け取る' : 'Retrieve',
    '友情Ptがありません' : 'There\'s no Friend points',
    'カードがありません' : 'There\'s no cards',
    'アイテムがありません' : 'There\'s no items',
    'ガチャ' : 'Shop',
    '強化する' : 'Go to upgrade',
    '4月転生アイテム' : 'April reborn Material',
    'ブーストアイテム' : 'Upgrade items',
    'アイテム' : 'Inventory',
    '枚' : ' unit',
    '売却する' : 'to card list',
    '受け取っていない贈り物はないみたいね。' : 'Looks like there\'s no gift waiting for you !',
    'まで' : ' is the limit date',
    'となります。' : ' to retrieve your items.',
    'ページ内全選択' : 'Select/Unselect all',
    '一括受取り' : 'Bulk retrieving',
    '合成する' : 'Synthesis',
    '合成' : 'Synthesis',
    '進化' : 'Evolution',
    '売却' : 'Card list',
    'アルバム' : 'Album',
    '入手が新しい順' : 'Newest first',
    '入手が古い順' : 'Oldest first',
    '一時保管所' : 'Temporary box',
    'を経過するとプレゼントBOXから消滅します｡' : '',
    '友情Pt' : ' Friend points',
    'カード' : 'Cards',
    'プレゼントBOX' : 'Gift Box',
    'その他' : 'Others',
    '個' : ' unit(s)',
    
};

// Friend points GACHA http://g12014827.sp.pf.mbga.jp/?url=http%3A%2F%2Fmb.hsdd.maql-games.jp%2Fsp%2Fgacha.html%3Fgacha_mode%3Dnormal
var fpGacha = {
    
    '期間限定イベント『プリンセスと、白馬の王子様!?』の実施期間内は最初の1回に引く無料ガチャが6連ガチャになるわよ！' : 'During this event, the free friend points gacha is a complete 6 cards gacha !',
    '友情Ptとは' : 'Friend Points FAQ',
    '注意事項' : 'Notes',
    '１回' : '1 card per ',
    '100友情Ptでガチャを1回引くことができるわ。' : 'You can purchase a random card for 100 Friends points.',
    '友情Ptが貯まれば何度でも引くことができるわよ！' : 'Earn Friends points by helping friends and by participing in special events !',
    '現状の友情Pt数' : 'Friend points reserve:',
    '友情Pt' : 'Friend Points',
    '・内容の詳細は、ラインナップからご覧ください。' : 'Check the lineup for more informations.',
    'アニメーションをスキップ' : 'Skip animations',
    '毎日最初の一回は無料で引くことができるのよ！' : 'Each day, the first Friend Gacha is free !',
    'さっそく引いてごらんなさい！' : 'Let\'s draw it !',
    'レジェンドチケット' : 'Legendary ticket',
    'チケット' : 'Gacha Tickets',
    'レジェンド' : 'Paid Gacha',
    '・ガチャは、ランダムでカードを獲得できます。1回の利用ごとに全ての出現カードが抽選対象となります。そのため、必ずしもご希望のカードが獲得できるとは限りません。また、ガチャで手に入るカードは重複する場合があります。' : 'The card you receive is randomly chosen. Therefore, it is not always possible to get the card you desire, and some card may not be available at a specific time.',
    '・ガチャのラインナップは変更になる場合があります。' : 'Lineup is subject to change.',
    '・ガチャの演出が最後まで表示されなかった場合、カード及びアイテムはプレゼントBOXへ正常に追加されていますのでご確認ください。' : 'Check if you received correctly the cards you got, if you have any problem, feel free to contact us.',
    '・ご購入頂いたガチャ・アイテムは届くまで時間がかかる場合がございますので、お時間をおいてプレゼントBOXをご確認ください。' : 'It may take some time for the cards to arrive in your Gift Box, if you don\'t see them, check later and contact support.',
    '・友情ガチャは午前0時ごろにリセットされます。' : 'Reset is everyday at midnight.',
    '※獲得するカードの最大ソケット数はレアリティにより異なります。' : 'The number of socket a card has depend on his rarity and if you\'re lucky or not. For each socket on a card, you can use an upgrade on it.',
    '-ソケットの最大数：C×1,UC×2,R×3,HR×3,SR×4,SSR×5,UR×6,W×6,' : '- The maximum number of socket (upgrades) per rarity is: C×1,UC×2,R×3,HR×3,SR×4,SSR×5,UR×6,W×6,',
    '友情ガチャ' : 'Friend points card drawing',
    '友情' : 'FP Gacha',
    'ガチャトップ' : 'Back to the shop',
    '合成' : 'Synthesis',
    '進化' : 'Evolution',
    '売却' : 'Card list',
    'ガチャ履歴確認' : 'Card history',
    'アルバム' : 'Album',
    'Boost!x6ガチャ' : 'Boost! x6 Gacha',
    'ガチャ' : 'Gacha',

};

// Login bonus
var loginBonus = {
    '最大戦闘力：' : 'Max ATK:',
    '最大HP：' : 'Max HP:',
    '進化度' : 'Evolution stade ',
    '[桜吹雪]ロスヴァイセは、' : 'Note that for this card,',
    '配布月のみジョーカー進化はできません。' : 'joker evolution isn\'t available.',
    'その他の報酬を確認する>>' : 'Check other rewards >>',
    'レジェンドチケット' : 'Gacha tickets',
    '最大連続ログイン日数 :' : 'Daily login streak: ',
    '現在累計' : 'You played ',
    '日ログイン中!' : ' days this month !',
    '開催期間：' : 'Availability: ',
};

var faq = {
    'ハイスクールD×Dとは' : 'High School DxD',
    'ハイスクールDxDについて' : 'High School DxD FAQ',
    'ハイスクールDxDとは' : 'What is High School DxD ?',
    'ハイスクールDxDはライトノベル原作、アニメも大人気の青春熱血ストーリーです。' : 'Highschool DxD is originally a light novel. It is now adapted as both a manga and an anime.',
    '本アプリではハイスクールDxDの魅力的なキャラクターたちがカードとなって登場します。' : 'The series revolves around Issei Hyoudou, a perverted high school student who is reincarnated into a Devil by Rias Gremory after being killed on his first date. He later joins the Occult Research Club as he strives to rise up the Devils\' ranks to fulfill his dream of building a harem and becoming a "Harem King".',
    '上級悪魔を目指して、自分だけのドリームチームを作りましょう。' : 'In this game, you\'ll be able to make your own team including devils and even angels (like Irina) or fallen angels (like Azazel or Raynare) !',
    'クエスト' : 'Quest',
    'クエストについて' : 'Q',
    'レーティングゲーム' : 'Rating game',

    'カード' : 'Cards',

    'デッキ' : 'Decks',

    'レイドボス' : 'Boss',

    'ギルド' : 'Guilds',
    '友達招待' : 'Friends referral',

    '友達' : 'Friends',

    'ガチャ' : 'Gacha',

    'アイテム' : 'Items',

    'プレゼントBOX' : 'GiftBox',

    'プロフィール' : 'Profile',


    '称号' : 'Title',

    'ログインボーナス' : 'Login Bonus',

    'スマートフォンの個人認証について' : 'Smartphone authentification',

    'ヘルプ一覧' : 'Back to main FAQ',
    'ヘルプ' : 'FAQ',
    'オープニングムービー' : 'Opening animation',
    'ビンゴムービー' : 'Bingo animation',
};

// Event medals box
var eventbox = {
    'レイドBOXガチャを引く' : 'Draw another Raid Box Gacha',
    'BOX内の残り' : 'Remaining prizes:',
    'レイドBOXガチャTOPへ' : 'Back to Raid Box Gacha',
    '・メダルはレイドボス撃破時やデイリーミッションの達成、ランキング報酬にて手に入れることができます。' : '・Medals can be acquired by defeating boss during the event, achieving daily mission or as ranking rewards.',
    '・次のBOXへ進んだ場合、変更前のBOX内にあるアイテムやカードは入手できなくなります。' : '・For each medal you use in a specific box, you get a random reward from that box.',
    '・A賞のカードを全て獲得後、任意で次のBOXへ進むことができます。' : '・Once you\'ve received every cards available in a specific box, you can choose to proceed to the next box.',
    '・過去のBOXで獲得しなかったカードが、BOX5で再度出現します。' : '・Note that items youn didn\'t get before proceeding will be available again in box 5.',
    '・レイドBOXガチャの内容は変更になる場合があります。' : '・Note that medals can\'t be used in a future event. Each medal is bound to the event it was gained in.',
    '・ガチャは、ランダムでアイテムを獲得できます。1回の利用ごとにBOXに残っている全てのカード、アイテムが抽選対象となります。' : '・Box contents are subject to change.',
    '・レイドBOXガチャは' : 'This Raid Box Gacha is available till ',
    'まで引くことができます。' : ' after this date, your remaining medals will be lost.',
    'レジェンドチケット 1枚' : 'Gacha Ticket x1',
    '※同一のアイテムが複数出現した際は' : '※Same item received multiple time',
    'まとめてからプレゼントBOXに送られます。' : 'are summed up into 1 stack.',
    'イベントTOPへ' : 'Back to event main page',
    '禁手 バランス・ブレイカ' : 'Balance Breaker',
    'プロモーション' : 'Promotion',
    'フェニックスの涙(小)' : 'Small Phenix Tears',
    'フェニックスの涙' : 'Phenix Tears',
    'レジェンドチケット x 1枚' : 'Gacha Ticket x1',
    'ドラゴンの血(小)' : 'Small Dragon Blood',
    'セイクリッドギア' : 'Sacred Gear',
    'ドラゴンの血' : 'Dragon Blood',
    '次のBOXの内容を確認' : 'Check next box details',
    'アニメーションをスキップ' : 'Skip animations',
    'メダルでガチャを引く' : 'Draw !',
    '所持メダル枚数 ' : 'You have: ',
    'メダル1枚で1回ガチャが引けます' : 'Each medal allow you to draw one random prize from the Gacha !',
    'レイドBOXガチャとは' : 'Raid Box Gacha FAQ',
    'レイドBOXガチャは ' : 'Raid Box Gacha is available till ',
    'レイドボスを撃破してメダルを手に入れよう!' : 'Receive medals to draw rewards by defeating boss / raid boss !',
    'レイドBOXガチャ' : 'Raid Box Gacha',
    '残り' : 'Remaining: ',
    ' まで!!' : '',
    '枚' : ' Medals',
    'メダル' : 'Medals',
    '個' : '',
    '友情Pt' : ' Friend points',
    'ピース' : ' Money',
    '4月転生アイテム' : 'April reborn Material',
    '合成' : 'Synthesis',
    '進化' : 'Evolution',
    '売却' : 'Card list',
    'アルバム' : 'Album',
    '注意事項' : 'Notes',
    '戦闘力' : 'ATK',
};

// Raid battle
var raidbattle = {
    '逃亡まで' : 'Time left: ',

    'オーバーブースト効果発動中!!' : 'Overboost effect triggered !!',
    'もう一度攻撃' : 'Boost again !',
    '通常攻撃' : 'Boost',
    '魔力20消費' : '-20MP',
    '魔力60消費' : '-60MP',
    '魔力100消費' : '-100MP',
    '魔力消費が多いほど' : 'Damages are increased according to ',
    'スキル発動率アップ' : 'magic consumption ',
    'レイドボス覚醒率' : 'Boss has ',
    'アップ中!' : ' chance to awake !',
    '3倍攻撃' : 'Boost x3',
    'ドラゴンの血(小)1個' : '-1 small blood',
    'ドラゴンの血(小)2個' : '-2 small blood',
    'ドラゴンの血(小)3個' : '-3 small blood',
    'ドラゴンの血(小)4個' : '-4 small blood',
    'ドラゴンの血(小)5個' : '-5 small blood',
    '5倍攻撃' : 'Boost x5',
    '魔力100回復して攻撃!' : 'Dragon blood consumption regains 100MP !',
    '(発見者報酬)' : '(Discoverer reward)',
    '(撃破者報酬)' : '(Finisher reward)',
    '発見者' : 'Discoverer',
    '撃破者' : 'Finisher',
    '攻撃デッキ' : 'Your deck',
    '★オーバーブースト発動!!★' : '★Overboost triggered!!★',
    'オーバーブーストカード：' : 'Cards with Overboost: ',
    '枚' : ' pieces',
    '撃破報酬' : ' defeat rewards:',
    'ドラゴンの血(小)：残り' : 'Small dragon blood owned : ',
    'ドラゴンの血：残り' : 'You have: ',
    '個' : ' unit(s)',
    'オーバーブースト効果を考慮した' : 'Optimize your deck',
    'オススメデッキに更新' : '(with Overboost effect included)',
    'イベントデッキ編成' : 'Go to decks management',
    'バトルアニメーションをスキップ' : 'Skip battle animation',
    '友達・ギルドメンバーに' : 'Call your friends and guildmates ! ',
    '友達に' : 'Call four friends ! ',
    '救援要請' : '(they will be able to help you, but will get a part of the reward)',
    'イベントクエストに戻る' : 'Back to quest',
    'イベントTOPへ' : 'Back to event main page',
    '魔力' : 'MP',
    '戦闘力：' : 'ATK：',
    'イベントクエストを続ける' : 'Continue Quest',
    '購入はこちら>>' : 'Purchase here',
    'あと' : 'Still ',
    '回撃破' : ' more kills',
    'で撃破数報酬獲得！' : ' to get a bonus reward！',
    'デイリーミッション達成！' : 'Get daily mission rewards！',
    'フィーバーPt' : 'Fever Pt',
    'Dの証所持数:' : 'Proof of D:',
    '※「Dの証」はレイドボスを撃破することで獲得できます。' : '※You get proof of D by defeating bosses。',
    'メダル' : 'Medals',
    '※「Dの証」の所持上限数を超える場合、「Dのオーブ」を使用することはできません。' : 'You won\'t be able to use a D orb if your Proof of D reserve is nearly empty.',
    '本日のデイリーミッション' : 'Today daily missions',
    'ドラゴンの血(小)' : 'Small dragon blood',
    'セイクリッドギア' : 'Sacred Gear',
    'フェニックスの涙(小)' : 'Small phenix tears',
};

// Diary (event bonus)
var diary = {
    'DxD ダイアリー' : 'DxD event\'s diary bonus !',
    'イベント期間中は日記を付けるだけで' : 'During events, you can get free bonus',
    '報酬がもらえるぞ!' : 'just by posting diaries !',
    'ダイアリー報酬' : 'Diary reward',
    'ドラゴンの血(小)×10' : 'Small Dragon Blood x10',
    '報酬を受け取る' : 'To gift box',
    'イベントTOPへ' : 'To event mainpage',

};

// Error page
var error = {
    '画面表示の際、エラーが発生しました、恐れ入りますがマイページに戻って再度アクセスをお願い致します。' : 'An error has occured. We apology for the inconvenience.',
    'エラー' : 'Error',

};

// General word used on each page (ei menu or card pages)
var general = {
    '特定商取引法に基づく表示' : 'Check some legal details',
    '行動力：' : 'AP: ',
    '魔力：' : 'MP: ',
    '友情Pt：' : 'Friend PT: ',
    'ピース：' : 'Money: ',
    'カード：' : 'Cards: ',
    'ガチャ履歴確認' : 'Friend points card history',
    'ラインナップ' : 'Lineup',
    '【重要】プレゼントBOX仕様変更につきまして' : '[IMPORTANT]Gift box changes ; please read !',
    '音声再生に関する免責事項' : 'Sound disclaimer',
    '・端末によっては音声が再生できません' : 'Some device may not be able to play sounds',
    '・音量にご注意ください' : 'Check the volume !',
    'タッチしてみる' : 'Touch !',
};

// Cards and skills translation, merged in first place to avoid fucking up
var cardata = {
// Cards name    
    'リアス・グレモリー' : 'Rias Gremory',
    'リアス＆朱乃' : 'Rias & Akeno',
    'アーシア・アルジェント' : 'Asia Argento',
    '黒歌' : 'Kuroka',
    '紫藤イリナ' : 'Irina Shidou',
    'レイヴェル・フェニックス' : 'Ravel Phenex',
    'グレイフィア・ルキフグス' : 'Grayfia Lucifuge',
    'ロスヴァイセ' : 'Rossweisse',
    '姫島朱乃' : 'Akeno Himejima',
    '兵藤一誠' : 'Issei Hyoudou',
    'セラフォルー・レヴィアタン' : 'Serafall Leviathan',
    '塔城小猫' : 'Koneko Toujou',
    'ミラ' : 'Mira',
    '支取蒼那' : 'Sona Sitri',
    'レイナーレ' : 'Raynare',
    'ユーベルーナ' : 'Yubelluna',
    '天野夕麻' : 'Amano Yūma',
    '桐生藍華' : 'Aika Kiryuu',
    '真羅椿姫' : 'Tsubaki Shinra',
    'ゼノヴィア' : 'Xenovia Quarta',
    'サーゼクス・ルシファー' : 'Sirzechs Lucifer', 
    'ヴェネラナ・グレモリー' : 'Venelena Gremory',
    'リアスの使い魔' : 'Rias\' familiar',
    'ヴァーリ・ルシファー' : 'Vali Lucifer',
    'フリード・セルゼン' : 'Freed Sellzen',
    '木場祐斗' : 'Kiba Yuuto',
    'イザベラ' : 'Isabela',
    'シーリス' : 'Siris',
    'ギャスパー・ヴラディ' : 'Gasper Vladi',
    '雪蘭' : 'Xuelan',
    'ミルたん' : 'Mil-tan',
    '花戒桃' : 'Momo Hanakai',
    '由良翼紗' : 'Tsubasa Yura',
    '桃園モモ' : 'Momo Momozono',
    'カーラマイン' : 'Karlamine',
    'ドライグ' : 'Ddraig',
    '草下憐耶' : 'Reya Kusaka',
    'カラワーナ' : 'Kalawarner',
    '巡巴柄' : 'Tomoe Meguri',
    'バルパー・ガリレイ' : 'Valper Galilei',
    '仁村留流子' : 'Ruruko Nimura',
    'ミッテルト' : 'Mittelt',
    'ドーナシーク' : 'Dohnaseek',
    'ニィ' : 'Li',
    'リィ' : 'Ni',
// '天道' : '',    Reya Kusaka lookalike; what's here name ffs ? http://sp.pf-img-a.mbga.jp/12014827?url=http%3A%2F%2Fmb.hsdd.maql-games.jp%2Fsp%2Fimage%2Fcards%2FL5%2F1867_2MpzcwK0qmSHOqKNVSEDb3OpfJk9dRFC.jpg
    
// Next 2 must be checked ;
    'マリオン' : 'Marion',
    'ビュレント' : 'Bürent',
    '片瀬': 'Katase',
    '村山' : 'Murayama',
    'シュリヤー' : 'Shuriya',
    'オーフィス' : 'Ophis',
    '美南風' : 'Mihae',
    '松田' : 'Matsuda',
    '元浜' : 'Motohama',
    'ネル' : 'Nel',
    'イル' : 'Ile',
// Not sure
    '名護' : 'Nago',
    
    
// Sets name    
    '[クラシカル]' : '[Classic]',
    '[夏服]' : '[Summer]',
    '[ビキニ]' : '[Bikini]',
    '[ダンサー]' : '[Dancer]',
    '[アメジスト]' : '[Amethyst]',
    '[戦闘服]' : '[Combat]',
    '[紅小悪魔]' : '[Devils in Red]',
    '[紅小悪魔Ⅱ]' : '[Devils in Red II]',
    '[白小悪魔]' : '[Devils in White]',
    '[白小悪魔Ⅱ]' : '[Devils in White II]',
    '[黒小悪魔Ⅱ]' : '[Devils in Black II]',
    '[黒小悪魔Ⅲ]' : '[Devils in Black III]',
    '[桜吹雪]' : '[CherryBlossom]',
    '[白バニー]' : '[Bunny]',
    '[バニー]' : '[Bunny]',
    '[セーラー]' : '[Sailor]',
    '[悪魔]' : '[Devil]',
    '[堕天使]' : '[Fallen Angel]',
    '[ビーチ]' : '[Beach]',
    '[桃色小悪魔]' : '[Devils in Pink]',
    '[桃小悪魔Ⅱ]' : '[PeachDevil II]',
    '[桃小悪魔Ⅲ]' : '[PeachDevil III]',
    '[桃小悪魔Ⅲ+]' : '[PeachDevil III+]',
    '[ビスチェ]' : '[Bustier I]',
    '[ビスチェⅢ]' : '[Bustier III]',
    '[湯けむりⅡ]' : '[HotSpring II]',
    '[湯けむりⅢ]' : '[HotSpring III]',
    '[魔王]' : '[Satan]',     
    '[千夜]' : '[1001 nights]',
    '[マスコット]' : '[Mascot]',
    '[爆弾]' : '[Bomb]',
    '[ボンテージ]' : '[S&M]',
    '[白龍皇]' : '[White Dragon Emp.]',
    '[聖剣使い]' : '[Holysword user]',
    '[聖女]' : '[Saint]',
    '[赤い龍]' : '[Red Dragon]',
    '[パイレーツ]' : '[Pirates]',
    '[パイレーツⅡ]' : '[Pirates II]',
    '[プリンセス]' : '[Princess]',
    '[プリンセスⅢ]' : '[Princess III]',
    '[くノ一]' : '[Ninja]',
    '[くノ一Ⅱ]' : '[Ninja II]',
    '[チャイナⅣ]' : '[China IV]',
// OPHIS
    '[龍神]' : '[Dragon]',
// Promotion cards
    '1号＆2号＆3号' : '#1 & #2 & #3',
    '[ハッカドール]' : '[MintDoll]',
//Skills
    '自分の戦闘力を超絶UP' : 'Self Attack UP+',
    '自分の戦闘力を絶大UP' : 'Self Attack UP++',
    '自分の戦闘力を極大UP' : 'Self Attack UP+++',

    '味方全体の戦闘力を超絶UP' : 'Team Attack UP+',
    '味方全体の戦闘力を絶大UP' : 'Team Attack UP++',
    '味方全体の戦闘力を極大UP' : 'Team Attack UP+++',

    '味方全体の戦闘力を超絶UP' : 'Team Attack UP+',
    '味方全体の戦闘力を絶大UP' : 'Team Attack UP++',   
    '味方全体の戦闘力を極大UP' : 'Team Attack UP+++',

    '味方全体のHPを超絶回復' : 'Team HP Restoration +',
    '味方全体のHPを絶大回復' : 'Team HP Restoration ++',
    '味方全体のHPを極大回復' : 'Team HP Restoration +++',
    
//    '同じ悪魔の駒で味方の戦闘力を超絶UP' : '+',
//    '同じ悪魔の駒で味方の戦闘力を絶大UP' : '++',
//    '同じ悪魔の駒で味方の戦闘力を極大UP' : '+++',
    
    '敵のHPを小DOWN' : 'Opponent HP DOWN-',
    
    '同じ悪魔の駒で敵のHPを小DOWN' : 'Opponent same role HP DOWN-',
    
    '敵全体のHPを超絶DOWN' : 'Opponents HP DOWN-',
    '敵全体のHPを絶大DOWN' : 'Opponents HP DOWN--',    
    '敵全体のHPを極大DOWN' : 'Opponents HP DOWN---',
    
   
};


// 
var full = {
};
